name: PR pipeline
on:
  pull_request:

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Clippy
        run: cargo clippy

      - name: Run rustfmt
        run: cargo fmt --check

      - name: Push docker image release
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: cnieg/gitlab-tokens-exporter:latest
